


export enum TipoPago {
    EFECTIVO = "EFECTIVO",
    TRANSFERENCIA = "TRANSFERENCIA",
    CHEQUE = "CHEQUE",
    TARJETA = "TARJETA",
    OTRO = "OTRO"
  }
  
  export enum Sucursal {
  ACAPULCO= 'ACAPULCO',
  AKUMAL= 'AKUMAL',
  BLUELINE= 'BLUELINE',
  CABOS= 'CABOS',
  CABOS_ACAPULCO= 'CABOS_ACAPULCO',
  CANCUN= 'CANCUN',
  CANCUN_BLUE_LINE= 'CANCUN_BLUE_LINE',
  CANCUN_PLAYA= 'CANCUN_PLAYA',
  CLM= 'CLM',
  CLMFA= 'CLMFA',
  COACH_LINE= 'COACH_LINE',
  COACH_LINE_CANCUN= 'COACH_LINE_CANCUN',
  MAHAHUAL= 'MAHAHUAL',
  MAZATLAN= 'MAZATLAN',
  PDC= 'PDC',
  PLAYA_DEL_CARMEN= 'PLAYA_DEL_CARMEN',
  PUERTO_AVENTURAS= 'PUERTO_AVENTURAS',
  PUERTO_MORELOS= 'PUERTO_MORELOS',
  TEPEAPULCO= 'TEPEAPULCO',
  TULUM= 'TULUM',
  VALLARTA= 'VALLARTA',
  YUCATAN= 'YUCATAN'
  }
export enum Region{

  QUINTANA_ROO = "QUINTANA_ROO",
  PTO_VALLARTA = "PTO_VALLARTA",
  HIDALGO = "HIDALGO",
  ACAPULCO = "ACAPULCO",
  CABOS = "CABOS",
  COACH_LINE = "COACH_LINE",
}
export enum EstadoFactura {
  PENDIENTE = 'Pendiente',
  PAGADA = 'Pagada',
  VENCIDA = 'Vencida',
  CANCELADA = 'Cancelada'
}

export enum TipoPagoExterno {
  COBROS_EFECTIVO_RIVIERA = 'COBROS_EFECTIVO_RIVIERA',
  COBROS_EFECTIVO_NORTE = 'COBROS_EFECTIVO_NORTE',
  COBROS_PACIFICO_BANCO = 'COBROS_PACIFICO_BANCO',
  COBROS_PACIFICO_EFECTIVO = 'COBROS_PACIFICO_EFECTIVO',
  COBRANZA_NORTE_BANCO = 'COBRANZA_NORTE_BANCO',
  COBROS_EFECTIVO_CDMX = 'COBROS_EFECTIVO_CDMX',
  CUENTA_NASSIM = 'CUENTA_NASSIM'
}